apiVersion: metrics.keptn.sh/v1
kind: AnalysisValueTemplate
metadata:
  name: energy-usage
spec:
  provider:
    name: prometheus
  query: '(sum(kepler_container_joules_total{pod_name=~"{{.pod}}.*",container_namespace="{{.ns}}"})/sum(kepler_container_joules_total{container_namespace="{{.ns}}"}))*100'
