apiVersion: metrics.keptn.sh/v1
kind: KeptnMetricsProvider
metadata:
  name: prometheus-provider
spec:
  type: prometheus
  targetServer: "http://PROMETHEUS_SERVER_TO_REPLACE.prometheus.svc.cluster.local:9090"
---
apiVersion: metrics.keptn.sh/v1
kind: KeptnMetricsProvider
metadata:
  name: dynatrace
spec:
  type: dynatrace
  targetServer: "TENANTURL_TOREPLACE"
  secretKeyRef:
    name: dynatrace
    key: dt_api_token
---
apiVersion: metrics.keptn.sh/v1
kind: KeptnMetricsProvider
metadata:
  name: dynatrace-dql
spec:
  type: dql
  targetServer: "TENANTURL_TOREPLACE"
  secretKeyRef:
    name: dynatrace
    key: dt_api_token